model_list:
  - model_name: "gpt-4o-mini"
    litellm_params:
      model: "gpt-4o-mini"
      custom_llm_provider: "openai"
  - model_name: "gpt-4o"
    litellm_params:
      model: "gpt-4o"
      custom_llm_provider: "openai"
  - model_name: "qwen-3-coder-480b"
    litellm_params:
      model: "qwen-3-coder-480b"
      custom_llm_provider: "cerebras"

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
  infer_model_from_keys: false

  # Pass through /v1/messages to custom adapter
  pass_through_endpoints:
    - path: "/v1/messages"
      target: custom_callbacks.anthropic_adapter   # Python instance
      headers:
        # Client API key extraction (either works)
        litellm_user_api_key: "authorization"      # e.g. "Bearer sk-..."
      forward_headers: true                        # Forward received headers to adapter

litellm_settings:
  # Structured logging callback (JSON lines to stdout)
  callbacks: custom_callbacks.adapter_logger
