[project]
name = "litellm-vercel"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "litellm[proxy]>=1.42.0"
]

[project.optional-dependencies]
test = [
  "pytest>=8.0.0",
  "pytest-asyncio>=0.21.0",
  "httpx>=0.25.0",
  "responses>=0.24.0",
  "pytest-snapshot>=0.9.0"
]