service: litellm-proxy-lambda

# Serverless Framework v4 - .env files are loaded automatically
# Stage-specific .env files: .env.${sls:stage} will be loaded if present

provider:
  name: aws
  runtime: python3.11
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  ecr:
    images:
      litellm-image:
        path: ./
        file: Dockerfile
  environment:
    # Basic Auth configuration
    BASIC_AUTH_USERNAME: ${env:BASIC_AUTH_USERNAME}
    BASIC_AUTH_PASSWORD: ${env:BASIC_AUTH_PASSWORD}
    # LiteLLM configuration
    DATABASE_URL: ${env:DATABASE_URL, ''}
    STORE_MODEL_IN_DB: ${env:STORE_MODEL_IN_DB, 'False'}
    MASTER_KEY: ${env:MASTER_KEY, ''}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, ''}
    ANTHROPIC_API_KEY: ${env:ANTHROPIC_API_KEY, ''}
    LITELLM_LOG: ${env:LITELLM_LOG, 'INFO'}

functions:
  proxy:
    image:
      name: litellm-image
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: ANY
    timeout: 30
    memorySize: 1024
    reservedConcurrency: 10

# Docker image deployment - no Python requirements plugin needed